version: '3.9'
services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
    - ./data/db:/data/db
    networks:
      - backend
    #environment:
    #- MONGO_INITDB_ROOT_USERNAME=admin
    env_file: .env

  flask:
    build: ./
    ports:
    - 5011:5000
    volumes:
      - ./src:/src
    networks:
      - frontend
      - backend
    env_file: .env


networks:
  frontend:
  backend: