apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: example
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: mongo
  resources:
    requests:
      storage: 30Mi