apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: example
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
status:
  loadBalancer: {}